name: pyrolitedocs

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pip:
      - -e git+https://github.com/morganjwilliams/pyrolite.git@develop#egg=pyrolite[dev,skl,excel]
